name: Checkout and Create Release Version

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 2 * * *'   # GitHub Actions 使用 UTC
  workflow_dispatch:

# 允许本工作流创建/更新 Release 资产
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Version
        id: get-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          # 用官方仓库拿 1Panel 最新版本，避免 fork 没有资产
          version=$(curl -sH "Authorization: Bearer ${GITHUB_TOKEN}" \
            https://api.github.com/repos/1Panel-dev/1Panel/releases/latest | jq -r '.tag_name')

          docker_version=$(curl -sH "Authorization: Bearer ${GITHUB_TOKEN}" \
            https://api.github.com/repos/moby/moby/releases/latest | jq -r '.tag_name')

          compose_version=$(curl -sH "Authorization: Bearer ${GITHUB_TOKEN}" \
            https://api.github.com/repos/docker/compose/releases/latest | jq -r '.tag_name')

          if [ -z "${version}" ] || [ "${version}" = "null" ]; then
            echo "Failed to get version"
            exit 1
          fi

          # 输出供后续步骤使用
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "app_version=${version}" >> $GITHUB_OUTPUT
          echo "docker_version=${docker_version#v}" >> $GITHUB_OUTPUT   # 去掉前缀 v
          echo "compose_version=${compose_version}" >> $GITHUB_OUTPUT

          echo "Current app_version: $version, docker_version: ${docker_version#v}, compose_version: $compose_version"

      - name: Check Release
        id: check-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 不存在则标记需要创建
          gh release view ${{ steps.get-version.outputs.version }} -R ${{ github.repository }} >/dev/null 2>&1 || echo "create=1" >> $GITHUB_OUTPUT

      - name: Check Build
        id: check-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 用 JSON 精确检查是否已有离线资产（任意架构都行，至少有一个才算已构建）
          has_any_offline=$(gh release view ${{ steps.get-version.outputs.version }} -R ${{ github.repository }} \
            --json assets --jq '.assets[].name | select(test("^1panel-.*-offline-linux-.*\\.tar\\.gz$"))' || true)

          if [ -z "$has_any_offline" ]; then
            echo "build=1" >> $GITHUB_OUTPUT
          fi

      - name: Create Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          sed -i "s@VERSION=v.*@VERSION=${{ steps.get-version.outputs.version }}@" install.sh
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Release ${{ steps.get-version.outputs.version }}" || true
          git tag -a "${{ steps.get-version.outputs.version }}" -m "Release ${{ steps.get-version.outputs.version }}" || true
          git push origin "${{ steps.get-version.outputs.version }}" || true

      - name: Create Release
        if: steps.check-release.outputs.create == 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.get-version.outputs.version }} --notes "Release ${{ steps.get-version.outputs.version }}" -R ${{ github.repository }}

      - name: Make Offline
        if: steps.check-build.outputs.build == 1
        env:
          # 让 prepare.sh 从官方仓库拉 release 资产；只构建 aarch64/x86_64（需要更多就改这里）
          APP_REPO: 1Panel-dev/1Panel
          ARCH_LIST: "aarch64 x86_64"
        run: |
          set -e
          chmod +x prepare.sh
          sudo APP_REPO="$APP_REPO" ARCH_LIST="$ARCH_LIST" ./prepare.sh \
            --app_version "${{ steps.get-version.outputs.app_version }}" \
            --docker_version "${{ steps.get-version.outputs.docker_version }}" \
            --compose_version "${{ steps.get-version.outputs.compose_version }}"

      - name: Upload Assets
        if: steps.check-build.outputs.build == 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          shopt -s nullglob
          # 先尝试标准目录 build/<version>/，否则退回到 build/
          files=(build/${{ steps.get-version.outputs.version }}/*.tar.gz)
          if [ ${#files[@]} -eq 0 ]; then
            files=(build/*.tar.gz)
          fi
          if [ ${#files[@]} -eq 0 ]; then
            echo "No .tar.gz files found to upload." >&2
            exit 1
          fi
          echo "Uploading: ${files[*]}"
          gh release upload ${{ steps.get-version.outputs.version }} "${files[@]}" -R ${{ github.repository }} --clobber

          # checksums 也做双路径兜底
          if [ -f "build/${{ steps.get-version.outputs.version }}/checksums.txt" ]; then
            gh release upload ${{ steps.get-version.outputs.version }} "build/${{ steps.get-version.outputs.version }}/checksums.txt" -R ${{ github.repository }} --clobber
          elif [ -f "build/checksums.txt" ]; then
            gh release upload ${{ steps.get-version.outputs.version }} "build/checksums.txt" -R ${{ github.repository }} --clobber
          else
            echo "checksums.txt not found, skip."
          fi
